いいね機能の実装
shinonome-inc/backend-final-assignment-koya1 pull request #6
Opened 2024-05-14 08:27 UTC by kou1205

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-05-15 10:43 UTC, SShizawa requested changes

2024-05-15 10:43 UTC, SShizawa commented on templates/accounts/profile.html
>  {% for tweet in object_list %}
accounts/views.py 内の UserProfileView で各ツイートがいいねされているかの情報を context に渡してください

2024-05-21 04:19 UTC, tatsurou9003 reviewed
クエリの重複とかもないんで上手く記述できてると思います。ただ、全体の動作確認してからpushするのをお忘れなく👍

2024-05-21 04:19 UTC, tatsurou9003 commented on templates/tweets/home.html
> +        <button type="button" class="like-button" id="like-button-{{ tweet.id }}" data-tweet-id="{{ tweet.id }}" data-liked="true">いいね取り消し</button>
味気ないからハートicon入れちゃおう。他の人はlikeのフォーマット定義したhtmlファイル切り出してる人多いけど、別に切り出さなくてOK。

2024-05-21 04:19 UTC, tatsurou9003 commented on templates/base.html
>  <!DOCTYPE html>
headerの画面遷移で、Twitter Cloneじゃなくてhomeの方がわかりやすい。細かくてすまんね。

2024-05-21 04:19 UTC, tatsurou9003 commented on tweets/tests.py
> +    def setUp(self):
各testクラスのsetupで似たような処理書いてるんで、setup用にTestCase継承したクラス作ってそれを継承する形にしたら、テストコード全体を簡潔にできるのでやってほし。

2024-05-21 04:19 UTC, tatsurou9003 commented on templates/tweets/home.html
> +    <div class="tweet">
detailに画面遷移する記述がない。

2024-05-21 04:21 UTC, tatsurou9003 commented on templates/tweets/home.html
> +    <div class="tweet">
detailから他者のprofileに飛べるようにしよう、tweetの所有者でprofile指定してあげるといいと思います。

2024-05-21 18:09 UTC, tatsurou9003 reviewed
similarになってるのは解消できるはず。
![スクリーンショット 2024-05-22 3 07 46](https://github.com/shinonome-inc/backend-final-assignment-koya/assets/99654281/2c367fbd-c6d1-44e0-b875-df90248a8c3e)

2024-05-21 18:09 UTC, tatsurou9003 commented on accounts/views.py
>      def get_queryset(self):
ユーザーIDで引っ張ってくるときにクエリ重複してる

2024-05-21 18:09 UTC, tatsurou9003 commented on tweets/views.py
detailViewでクエリの重複が発生してる

2024-05-21 18:10 UTC, tatsurou9003 commented
個人開発なら問題ないですが、実務の場合はcommitメッセージをわかりやすく記述するのを心がけてください。どこまで戻せばいいかわからなくなるので。

2024-05-22 02:28 UTC, merged

2024-05-22 02:28 UTC, tatsurou9003 commented
LGTM